### ISSUE TITLE
Cannot dynamically set region / aws profile based on known Hiera configuration

### ISSUE THREAD

**Issue by raffraffraff** [raffraffraff/hiera_aws_ssm_parameter_store#9]
It's not possible to use interpolation of known Hiera variables in the plugin options, like this:

```
  - name: secrets
    lookup_key: "aws_ssm_parameter"
      options:
        region: %{aws_region}
        aws_profile: %{aws_profile}
```

There's nothing I can do within this plugin to fix that because it appears to be a limitation of the Go hierasdk. I just wanted to track it here while I think about workarounds.

My hot-take on it is that maybe it's fine to hard-code a specific region and AWS profile, and treat that AWS account, region and SSM Parameter Store namespace as if it were an external service like 1Password, BitWarden, LastPass etc. Whether or not you're happy to do that depends on your interpretation of your company's internal security practices.
